stages:
  evaluate:
    cmd: python step_05_evaluate.py
    deps:
    - data/processed/X_test_scaled.csv
    - data/processed/y_test.csv
    - models/model.joblib
    - step_05_evaluate.py
    metrics:
    - metrics/metrics.json:
        cache: false
