stages:
  transformation:
    cmd: python step_01_transformation.py
    deps:
    - data/raw
    - step_01_transformation.py
    outs:
    - data/processed
  normalization:
    cmd: python step_02_normalization.py
    deps:
    - step_02_normalization.py
