data_transformation: 
  root_dir: data/processed
  data_path: data/raw/raw.csv

data_normalization:
  root_dir: data/processed

model_trainer:
  root_dir: models
  data_path: data/processed
  model_name: rf
  n_estimators: 100
  max_depth: 10